// styles/homescreen/HomeScreen.styles.js
import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  // LOADING STYLES
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#091429',
  },
  loadingText: {
    color: '#a0c0ff',
    marginTop: 12,
    fontSize: 16,
  },
  background: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },

  // NEW USER SCREEN STYLES
  newUserContainer: {
    flex: 1,
    backgroundColor: '#4A90E2',
  },
  newUserBackgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: width,
    height: height,
    zIndex: 1,
  },
  newUserSafeArea: {
    flex: 1,
    zIndex: 2,
  },
  newUserContentContainer: {
    flex: 1,
    paddingHorizontal: 20,
    justifyContent: 'space-between',
  },
  newUserTopSpacer: {
    flex: 1,
  },
  newUserTextContainer: {
    flex: 0.4,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  newUserMainTitle: {
    fontSize: 42,
    fontWeight: '600',
    color: '#ffffff',
    textAlign: 'center',
    lineHeight: 48,
    marginBottom: 20,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  newUserSubtitle: {
    fontSize: 16,
    color: '#ffffff',
    textAlign: 'center',
    lineHeight: 22,
    opacity: 0.9,
    fontWeight: '400',
    marginBottom: 60,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  newUserButtonContainer: {
    flex: 0,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingBottom: 10,
  },
  newUserGetStartedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 20,
    width: width * 0.85,
    maxWidth: 280,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    marginBottom: 40,
  },
  newUserButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333333',
    flex: 1,
    textAlign: 'center',
    marginRight: 40,
  },
  newUserButtonIcon: {
    position: 'absolute',
    right: 10,
    width: 45,
    height: 45,
    borderRadius: 15,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // DASHBOARD STYLES
  container: {
    flex: 1,
    backgroundColor: '#091429',
  },
  fixedTopSection: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: Platform.OS === 'android' ? height * 0.65 : height * 0.65,
    zIndex: 0,
  },
  gradientBackground: {
    flex: 1,
    paddingTop: 40,
  },
  scrollView: {
    flex: 1,
    zIndex: Platform.OS === 'android' ? 50 : 2,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  scrollSpacer: {
    height: Platform.OS === 'android' ? height * 0.4 : height * 0.45,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 25,
  },
  headerLeft: {
    flex: 1,
  },
  greeting: {
    fontSize: 18,
    color: '#a0c0ff',
    marginBottom: 6,
    fontWeight: '500',
    letterSpacing: 0.5,
    opacity: 0.9,
  },
  userName: {
    fontSize: 32,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: -0.5,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  avatar: {
   borderRadius: 25.5,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(56, 191, 167, 0.3)',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.45,
    shadowRadius: 4,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },

  // BODY OVERVIEW SECTION STYLES
  bodySection: {
    paddingHorizontal: 20,
    flex: 1,
    justifyContent: 'center',
    position: 'relative',
    zIndex: Platform.OS === 'android' ? 0 : 1,
    marginTop: Platform.OS === 'android' ? -50 : 0,
  },
  bodyContent: {
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  bodyTextSection: {
    flex: 0,
    paddingRight: 20,
    zIndex: 2,
  },
  bodyTitle: {
    marginBottom: 30,
  },
  bodyTitleLine1: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    lineHeight: 32,
    textShadowColor: 'rgba(56, 191, 167, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  bodyTitleLine2: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#38BFA7',
    lineHeight: 32,
    textShadowColor: 'rgba(56, 191, 167, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  bodyStats: {
    gap: 20,
    marginBottom: 20,
  },
  bodyStat: {
    marginBottom: 10,
  },
  bodyStatNumber: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#fff',
    lineHeight: 48,
    textShadowColor: 'rgba(255, 255, 255, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  bodyStatLabel: {
    fontSize: 16,
    color: '#a0c0ff',
    marginTop: 4,
    fontWeight: '500',
  },
  bodyModelImage: {
    width: Platform.OS === 'android' ? '80%' : '100%',
    height: Platform.OS === 'android' ? '80%' : '100%',
    position: 'absolute',
    resizeMode: 'cover',
    marginLeft: Platform.OS === 'android' ? 150 : 120,
    zIndex: -1,
    marginBottom: -5,
  },
  encouragementContainer: {
    marginTop: 10,
  },
  encouragementText: {
    fontSize: 14,
    color: '#a0c0ff',
    marginBottom: 12,
    lineHeight: 18,
  },
  getStartedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(56, 191, 167, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(56, 191, 167, 0.3)',
    alignSelf: 'flex-start',
  },
  getStartedButtonText: {
    color: '#38BFA7',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 6,
  },

  // METRICS SECTION STYLES
  metricsSection: {
    backgroundColor: '#162F65',
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
    zIndex: Platform.OS === 'android' ? 100 : 3,
    marginTop: Platform.OS === 'android' ? 150 : 140,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  seeAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  seeAllText: {
    fontSize: 16,
    color: '#38BFA7',
    marginRight: 4,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },

  // HEALTH METRIC CARD STYLES
  healthMetricCard: {
    width: '48%',
    marginBottom: 16,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(56, 191, 167, 0.3)',
  },
  metricCardContainer: {
    flex: 1,
  },
  metricBackgroundIcon: {
    position: 'absolute',
    top: 10,
    right: -10,
    opacity: 0.3,
    zIndex: 1,
  },
  metricGlowEffect: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
    zIndex: 1,
  },
  metricCardContent: {
    position: 'relative',
    zIndex: 3,
    padding: 0,
    minHeight: 140,
  },
  statusGlow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 4,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    zIndex: 2,
  },
  leftMetricCard: {
    marginRight: '2%',
  },
  rightMetricCard: {
    marginLeft: '2%',
  },
  metricCardGradient: {
    padding: 20,
    minHeight: 140,
  },
  metricHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  metricStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 10,
  },
  metricType: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
    flex: 1,
  },
  metricValue: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  metricUnit: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 12,
  },
  metricDate: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.6)',
  },

  // ORGAN HEALTH CARD STYLES
  organHealthCard: {
    width: '48%',
    marginBottom: 16,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(56, 191, 167, 0.3)',
  },
  organCardContainer: {
    flex: 1,
  },
  organBackgroundIcon: {
    position: 'absolute',
    top: 10,
    right: -10,
    opacity: 0.3,
    zIndex: 1,
  },
  organGlowEffect: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
    zIndex: 1,
  },
  organCardContent: {
    position: 'relative',
    zIndex: 3,
    padding: 0,
    minHeight: 160,
  },
  organCardGradient: {
    padding: 20,
    minHeight: 160,
  },
  organHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  organIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  organName: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
    flex: 1,
  },
  organScoreContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 4,
  },
  organHealthScore: {
    fontSize: 36,
    fontWeight: 'bold',
    lineHeight: 40,
  },
  organScoreLabel: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '600',
    marginLeft: 4,
  },
  organScoreStatus: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 12,
  },
  organPrimaryMetric: {
    marginBottom: 12,
  },
  organPrimaryMetricName: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 2,
  },
  organPrimaryMetricValue: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
  },
  organMetricCount: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.6)',
  },
  organStatusIndicator: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 4,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    zIndex: 2,
  },

  // REPORTS SECTION STYLES
  reportsSection: {
    backgroundColor: '#162F65',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
  },
  reportCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  reportIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(56, 191, 167, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  reportInfo: {
    flex: 1,
  },
  reportTitle: {
    fontSize: 16,
    fontWeight: '600',
    textTransform:'uppercase',
    color: '#fff',
    marginBottom: 4,
  },
  reportDate: {
    fontSize: 14,
    color: '#a0c0ff',
    marginBottom: 2,
  },
  reportStatus: {
    fontSize: 13,
    color: '#a0c0ff',
  },
  noReportsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  noReportsText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
    marginBottom: 4,
  },
  noReportsSubtext: {
    fontSize: 14,
    color: '#a0c0ff',
    marginBottom: 16,
    textAlign: 'center',
  },
  uploadButton: {
    backgroundColor: 'rgba(56, 191, 167, 0.2)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(56, 191, 167, 0.3)',
  },
  uploadButtonText: {
    color: '#38BFA7',
    fontSize: 14,
    fontWeight: '600',
  },

  // BRAND SECTION STYLES
  fullScreenBrandSection: {
    minHeight: height,
    width: width,
    zIndex: 5,
  },
  brandFullGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    position: 'relative',
  },
  brandDecorative: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  decorativeCircle1: {
    position: 'absolute',
    top: '10%',
    right: '5%',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(56, 191, 167, 0.1)',
  },
  decorativeCircle2: {
    position: 'absolute',
    bottom: '15%',
    left: '8%',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(44, 123, 229, 0.15)',
  },
  decorativeCircle3: {
    position: 'absolute',
    top: '30%',
    left: '10%',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(56, 191, 167, 0.08)',
  },
  decorativeCircle4: {
    position: 'absolute',
    bottom: '30%',
    right: '15%',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  brandFullContent: {
    alignItems: 'center',
    zIndex: 2,
  },
  brandIconContainer: {
    position: 'relative',
    marginBottom: 40,
  },
  brandIconGlow: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(56, 191, 167, 0.2)',
    top: -10,
    left: -10,
    zIndex: 1,
  },
  brandIcon: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
    borderWidth: 2,
    borderColor: 'rgba(56, 191, 167, 0.3)',
  },
  brandTextContainer: {
    alignItems: 'center',
    marginBottom: 30,
  },
  brandMainText3D: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 2, height: 3 },
    textShadowRadius: 6,
  },
  brandSubText3D: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#38BFA7',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 2, height: 3 },
    textShadowRadius: 8,
  },
  brandNameContainer3D: {
    alignItems: 'center',
    marginBottom: 40,
  },
  brandName3D: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 3,
    textShadowColor: 'rgba(0, 0, 0, 0.6)',
    textShadowOffset: { width: 3, height: 4 },
    textShadowRadius: 10,
  },
  brandProduct3D: {
    fontSize: 18,
    fontWeight: '600',
    color: 'rgba(160, 192, 255, 0.9)',
    letterSpacing: 2,
    marginTop: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 4,
  },
  featureHighlights: {
    alignItems: 'flex-start',
    marginBottom: 40,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  featureText: {
    fontSize: 16,
    color: '#a0c0ff',
    marginLeft: 12,
    fontWeight: '500',
  },
  enhancedCTAButton: {
    borderRadius: 30,
    overflow: 'hidden',
    elevation: 6,
    shadowColor: '#38BFA7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  ctaGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingVertical: 16,
  },
  ctaButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginRight: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },

  // SHARED STYLES
  bottomPadding: {
    height: -20,
  },
});